FROM nginx:1.27-alpine

RUN apk add --no-cache apache2-utils

COPY deploy2/nginx/app.conf /etc/nginx/conf.d/default.conf
COPY deploy2/nginx/10-basic-auth.sh /docker-entrypoint.d/10-basic-auth.sh

RUN chmod +x /docker-entrypoint.d/10-basic-auth.sh

